#!/bin/sh

if [ "${MYSQL_STATISTICS}" = "false" ]
then
  sudo bash -c  'echo "column-statistics=0" >> /etc/mysql/conf.d/mysqldump.cnf'
fi

# Disable StrictHostKeyChecking
echo "    StrictHostKeyChecking no" | sudo tee -a /etc/ssh/ssh_config

#Set SSH Password
echo "aegir:${AEGIR_SSH_PWD}" | chpasswd

#Change apache vars
sudo sed -i "s/APACHE_RUN_USER=www-data/APACHE_RUN_USER=$APACHE_RUN_USER/g" /etc/apache2/envvars
sudo sed -i "s/APACHE_RUN_GROUP=www-data/APACHE_RUN_GROUP=$APACHE_RUN_GROUP/g" /etc/apache2/envvars

set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

sudo /etc/init.d/ssh start
/etc/init.d/php7.3-fpm start
sudo a2enconf php-fpm
sudo /usr/sbin/apache2ctl start
tail -f /var/log/apache2/*.log